#' Extract ComparisonResult from a MSstats group comparision object
#'
#' @description This function extracts a named comparision result from an object returned by MSstats::groupComparison()
#'
#' @details Acessor function for named $ComparisonResult. In case you would like to inpect which comparisions are available use \code{\link[posprot]{get.comparision.labels}}. An empty data.frame is returned if the requested comparision does not exist.
#'
#' @param x A group comparision result as generated by \code{\link[MSstats]{groupComparison}}
#'
#' @param label Name of the comparision (character) to extract from x
#'
#' @return data.frame
#'
#' @export
#'
#' @examples n <- get.comparison.labels(sample.data)
#' n[1]
#' get.MSstats_gcr(sample.data, n[1])
#'
get.MSstats_gcr <- function(x, label){
  stopifnot(is.MSstats_gcr(x), class(label) == "character")
  x$ComparisonResult[x$ComparisonResult$Label == label,]
}
